name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: helenamarcomini22
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualiza cobrinha das contribuições 🐍"
          add: "github-contribution-grid-snake.svg"
